// Generates src/assets/themes.css from src/shared/brand.ts.
//
//   node scripts/build-themes.mjs           # write the file
//   node scripts/build-themes.mjs --check   # fail if it is stale
//
// The generated file holds only *seeds*: the ten brand tokens per palette plus
// the handful of values that cannot be expressed as a CSS derivation (the
// contrast-picked ink colours). Everything else — all 26 UI variables — is
// derived from those seeds by the hand-written assets/theme-base.css, so a new
// theme costs ten colours rather than twenty-six.
import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { PALETTES } from '../src/shared/brand.ts';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '..', 'src', 'assets', 'themes.css');

// ---- contrast --------------------------------------------------------------
const rgb = (h) => [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16));
const lum = (c) => {
  const f = (v) => ((v /= 255) <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4);
  return 0.2126 * f(c[0]) + 0.7152 * f(c[1]) + 0.0722 * f(c[2]);
};
const contrast = (a, b) => {
  const [x, y] = [lum(rgb(a)), lum(rgb(b))].sort((p, q) => q - p);
  return (x + 0.05) / (y + 0.05);
};
const mix = (a, b, t) =>
  '#' + rgb(a).map((v, i) => Math.round(v + (rgb(b)[i] - v) * t).toString(16).padStart(2, '0')).join('');

/**
 * Ink that reads on a filled surface. The palette's own text and ground come
 * first because they keep the theme coherent, but if neither clears 4.5 the
 * pure extremes win — a legible button beats a tonally tidy one.
 */
const inkOn = (bg, p) => {
  const best = [p.text, p.ground, '#ffffff', '#000000']
    .map((ink) => ({ ink, r: contrast(bg, ink) }))
    .sort((a, b) => b.r - a.r);
  const own = [p.text, p.ground]
    .map((ink) => ({ ink, r: contrast(bg, ink) }))
    .sort((a, b) => b.r - a.r)[0];
  return own.r >= 4.5 ? own.ink : best[0].ink;
};

// CSS cannot pick a contrasting ink, so these two are resolved here. Both are
// measured against the *filled* colour the ink actually sits on.
const onAccent = (p) => inkOn(p.pin?.['--accent-dim'] ?? mix(p.accent, p.ground, 0.24), p);
const onDanger = (p) => inkOn(p.pin?.['--danger'] ?? (p.scheme === 'light' ? '#c02626' : '#ef4444'), p);

// ---- emit ------------------------------------------------------------------
const seedBlock = (p) => {
  const lines = [
    ['--brand-tile', p.tile],
    ['--brand-ground', p.ground],
    ['--brand-back-1', p.back1],
    ['--brand-back-2', p.back2],
    ['--brand-front', p.front],
    ['--brand-dot', p.dot],
    ['--brand-accent', p.accent],
    ['--brand-bar-2', p.bar2],
    ['--brand-text', p.text],
    ['--brand-text-muted', p.textMuted],
    ['--brand-turn', p.turn],
    // the mark's on-panel role set, used by the sidebar lock-up
    ['--on-back-1', p.on.back1],
    ['--on-back-2', p.on.back2],
    ['--on-front', p.on.front],
    ['--on-dot', p.on.dot],
    ['--on-accent-bar', p.on.accent],
    ['--on-bar-2', p.on.bar2],
    // contrast-picked inks
    ['--on-accent', onAccent(p)],
    ['--on-danger', onDanger(p)],
  ];
  const decl = (rows) => rows.map(([k, v]) => `  ${k}: ${v};`).join('\n');
  const sel = `:root[data-theme='${p.id}']`;
  // The first palette also answers the bare :root, so an unknown or missing
  // data-theme still renders a complete set rather than nothing at all.
  const head = p.id === PALETTES[0].id ? `:root,\n${sel}` : sel;
  let css = `/* ${p.label} — ${p.note} */\n${head} {\n${decl(lines)}\n}\n`;
  const pin = Object.entries(p.pin ?? {});
  if (pin.length) {
    // Doubled :root so a pinned value always outranks the light/dark scheme
    // block in styles.css, whatever order the two stylesheets load in.
    css += `:root:root[data-theme='${p.id}'] {\n${decl(pin)}\n}\n`;
  }
  return css;
};

const body = `/* GENERATED by scripts/build-themes.mjs — edit src/shared/brand.ts instead.
 *
 * Seeds only. The UI variables are derived from these by assets/theme-base.css;
 * a palette's \`pin\` entries land here too, at higher specificity so they win.
 */

${PALETTES.map(seedBlock).join('\n')}`;

if (process.argv.includes('--check')) {
  const current = readFileSync(out, 'utf8').replace(/\r\n/g, '\n');
  if (current !== body) {
    console.error('themes.css is stale — run: node scripts/build-themes.mjs');
    process.exit(1);
  }
  console.log('themes.css is up to date');
} else {
  writeFileSync(out, body);
  console.log(`wrote src/assets/themes.css (${PALETTES.length} palettes)`);
}
